[package]
name = "fileforge-std"
version = "0.1.2"
edition = "2021"

[dependencies]
fileforge-lib = { version = "0.1.4", path = "../fileforge-lib", registry = "eepy", default-features = false }

[features]
default = ["std"]
std = ["fileforge-lib/alloc"]
