[package]
name = "fileforge-std"
version = "0.1.2"
edition = "2021"

[dependencies]
fileforge = { path = "../fileforge" }
fileforge-macros = { path = "../fileforge-macros" }

[features]
default = ["alloc", "std"]
std = ["fileforge/std"]
alloc = ["fileforge/alloc"]
